# Default settings

display:
  dark_mode: false
  # Not yet configurable
  md_primary_palette: 'Teal'
  md_accent_palette: 'Cyan'
inaturalist:
  locale: null
  preferred_place_id: 1
  username: null
  casual_observations: true
metadata:
  common_names: true
  create_xmp: true
  darwin_core: true
  hierarchical_keywords: true
photos:
  start_dir: '/'
  # Not yet configurable
  filetypes: ['jpg', 'jpeg', 'png', 'gif']
# Not yet configurable
search:
  autocomplete_delay: 0.5
  autocomplete_min_chars: 3
